version: '3.4'
services:
    mpeg-dash-server:
        # Use the sysctls tool to update the ignore broadcasts setting to false
        # https://docs.docker.com/compose/compose-file/#sysctls
        sysctls:
            - net.ipv4.icmp_echo_ignore_broadcasts=0
            - net.ipv6.conf.all.disable_ipv6=1
            - net.ipv6.conf.default.disable_ipv6=1
        build:
            context: .
            target: mpeg-dash-server
            network: bridge
        image:
            mpeg-dash-server
        ports:
            - "8080:8080"
            - "8088:8088"
        cap_add:
            - NET_ADMIN
        volumes:
            # Required for downlink traffic shaping ifb buffer
            - /lib/modules:/lib/modules
        privileged: true